# Generated by Django 3.2.3 on 2021-05-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.CharField(max_length=50, unique=True)),
                ('employeeRole', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Accountant', 'Accountant'), ('Librarian', 'Librarian'), ('Receptionist', 'Receptionist'), ('Super Admin', 'Superadmin')], max_length=50)),
                ('employeeDesignation', models.CharField(blank=True, choices=[('Faculty', 'Faculty'), ('Accountant', 'Accountant'), ('Admin', 'Admin'), ('Receptionist', 'Receptionist'), ('Director', 'Director'), ('Technical Head', 'Technical Head')], max_length=50)),
                ('employeeDepartment', models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Library', 'Library'), ('Sports', 'Sports'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Exam', 'Exam'), ('Admin', 'Admin'), ('Finance', 'Finance')], max_length=50)),
                ('employeeFirstName', models.CharField(blank=True, max_length=60, null=True)),
                ('employeeLastName', models.CharField(blank=True, max_length=60, null=True)),
                ('employeeFatherName', models.CharField(blank=True, max_length=60, null=True)),
                ('employeeEmail', models.EmailField(blank=True, max_length=254, unique=True)),
                ('employeeGender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('employeeEmergencyContactNumber', models.CharField(blank=True, max_length=17)),
                ('employeeMaritialStatus', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Not Specified', 'Not Specified')], default='Single', max_length=200)),
                ('employeeCurrentAddress', models.TextField(blank=True, max_length=300, null=True)),
                ('employeeParmanentAddress', models.TextField(blank=True, max_length=300, null=True)),
                ('employeeQualification', models.TextField(blank=True, max_length=300, null=True)),
                ('employeeWorkExperience', models.TextField(blank=True, max_length=300, null=True)),
                ('employeeNote', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
