# Generated by Django 3.2.3 on 2021-05-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210519_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employeeDateOfBirth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeeDateOfJoining',
        ),
    ]
