# Generated by Django 3.2.3 on 2021-05-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210520_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeDateOfJoining',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeePhone',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
