# Generated by Django 3.2.3 on 2021-05-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210520_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeDateOfBirth',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeDateOfJoining',
            field=models.DateTimeField(),
        ),
    ]
